### ISSUE TITLE
[ERR_IMPORT_ASSERTION_TYPE_MISSING]

### ISSUE THREAD

**Issue by nagarajpandith** [wooorm/character-entities#18]
hi @wooorm, my project is using [next-mdx-remote](https://www.npmjs.com/package/next-mdx-remote) which has a dependency with your package [character-entities](https://www.npmjs.com/package/character-entities/v/2.0.2). everything works fine on local, but throws an error in deployment on vercel. i've been trying to find a solution online, but nothing is available so far as it's not my code but the third party package throwing error.

<img width="1201" alt="Screenshot 2023-11-15 at 3 37 17 PM" src="https://github.com/wooorm/character-entities/assets/83623339/5de57c9d-3e70-4de5-a1fc-4453cdf15d14">

as far as i've researched about this error, they say it can be resolved by asserting a type during import, for example
`import countryTable from "./data/countries.json" with { type: "json" };`
but i won't be able to do it as the error is not in my code but the character-entities package instead.

**Comment by wooorm** [comment]
Hey! There is no JSON here: https://github.com/wooorm/character-entities/blob/main/index.js. For years.
I recommend asking `next-mdx-remote`/Vercel folks for errors. Perhaps they’re using pre-ESM versions which don’t work on Vercel.

**Comment by Cry0nicS** [comment]
@nagarajpandith did you find a solution for this, by any chance?
Run into the same issue now, with a Vue project. Only happens on Node v18. On 20+, there's no problem.

**Comment by wooorm** [comment]
See the comment before yours.

Update your tools
