### ISSUE TITLE
Can we split list to separate file-groups?

### ISSUE THREAD

**Issue by denisx** [wooorm/character-entities#19]
For some type or localizition, we dont need symbols like "greek" types or another type. It will be more comfortable to add separate exports. With main common type. It is minor adds, no majority.

(Can help with pr)

**Comment by wooorm** [comment]
How? Why? Which localization? What are “greek” types?

From your other issue, it sounds like you are dealing with markdown.
Why do want non-standard markdown?

As you are coming from micromark, this is probably not an issue for you: `character-entities` is not included in your browser bundle if you use a good bundler.
